/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_robotbase_carassistant_cardetection_NativeCarDetection */

#ifndef _Included_com_robotbase_carassistant_cardetection_NativeCarDetection
#define _Included_com_robotbase_carassistant_cardetection_NativeCarDetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_robotbase_carassistant_cardetection_NativeCarDetection
 * Method:    update
 * Signature: ([BII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_robotbase_carassistant_cardetection_NativeCarDetection_update
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     com_robotbase_carassistant_cardetection_NativeCarDetection
 * Method:    initCascade
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_robotbase_carassistant_cardetection_NativeCarDetection_initCascade
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
