/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aios_core_vision_facelearning_NativeFaceLearning */

#ifndef _Included_aios_core_vision_facelearning_NativeFaceLearning
#define _Included_aios_core_vision_facelearning_NativeFaceLearning
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aios_core_vision_facelearning_NativeFaceLearning
 * Method:    update
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_aios_core_vision_facelearning_NativeFaceLearning_update
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
