/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aios_core_vision_facerecognition_NativeFaceRecognition */

#ifndef _Included_aios_core_vision_facerecognition_NativeFaceRecognition
#define _Included_aios_core_vision_facerecognition_NativeFaceRecognition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aios_core_vision_facerecognition_NativeFaceRecognition
 * Method:    update
 * Signature: (Laios/core/vision/facerecognition/FaceRecognitionService;[BIILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_aios_core_vision_facerecognition_NativeFaceRecognition_update
  (JNIEnv *, jclass, jobject, jbyteArray, jint, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
