/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aios_core_vision_facedetection_NativeFaceDetectionCV */

#ifndef _Included_aios_core_vision_facedetection_NativeFaceDetectionCV
#define _Included_aios_core_vision_facedetection_NativeFaceDetectionCV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aios_core_vision_facedetection_NativeFaceDetectionCV
 * Method:    update
 * Signature: ([BII)V
 */
JNIEXPORT jstring JNICALL Java_aios_core_vision_facedetection_NativeFaceDetectionCV_update
  (JNIEnv *, jclass, jbyteArray, jint, jint);


/*
 * Class:     aios_core_vision_facedetection_NativeFaceDetectionCV
 * Method:    initCascade
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_aios_core_vision_facedetection_NativeFaceDetectionCV_initCascade
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
