/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aios_core_vision_facetracking_NativeFaceTracking */

#ifndef _Included_aios_core_vision_facetracking_NativeFaceTracking
#define _Included_aios_core_vision_facetracking_NativeFaceTracking
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aios_core_vision_facetracking_NativeFaceTracking
 * Method:    update
 * Signature: ([BIILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_aios_core_vision_facetracking_NativeFaceTracking_update
  (JNIEnv *, jclass, jbyteArray, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
