/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class robotbase_vision_camera_memory_NativeServer */

#ifndef _Included_robotbase_vision_camera_memory_NativeServer
#define _Included_robotbase_vision_camera_memory_NativeServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     robotbase_vision_camera_memory_NativeServer
 * Method:    setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_robotbase_vision_camera_memory_NativeServer_setup
  (JNIEnv *, jclass);

/*
 * Class:     robotbase_vision_camera_memory_NativeServer
 * Method:    writeData
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_robotbase_vision_camera_memory_NativeServer_writeData
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
