/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class robotbase_vision_NativeAndroidCamera */

#ifndef _Included_robotbase_vision_NativeAndroidCamera
#define _Included_robotbase_vision_NativeAndroidCamera
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     robotbase_vision_NativeAndroidCamera
 * Method:    getFrame
 * Signature: ([BIIJ[B)V
 */
JNIEXPORT void JNICALL Java_robotbase_vision_NativeAndroidCamera_getFrame
  (JNIEnv *, jclass, jbyteArray, jint, jint, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
