/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class robotbase_vision_NativeMotionDetection */

#ifndef _Included_robotbase_vision_NativeMotionDetection
#define _Included_robotbase_vision_NativeMotionDetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     robotbase_vision_NativeMotionDetection
 * Method:    processFrame
 * Signature: ([BIIJ)[I
 */
JNIEXPORT jintArray JNICALL Java_robotbase_vision_NativeMotionDetection_processFrame
  (JNIEnv *, jclass, jbyteArray, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
