/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class robotbase_vision_camera_NativeOpenni2 */

#ifndef _Included_robotbase_vision_camera_NativeOpenni2
#define _Included_robotbase_vision_camera_NativeOpenni2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     robotbase_vision_camera_NativeOpenni2
 * Method:    InitCamera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_robotbase_vision_camera_NativeOpenni2_InitCamera
  (JNIEnv *, jclass);

/*
 * Class:     robotbase_vision_camera_NativeOpenni2
 * Method:    GetImage
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_robotbase_vision_camera_NativeOpenni2_GetImage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     robotbase_vision_camera_NativeOpenni2
 * Method:    GetImageByte
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_robotbase_vision_camera_NativeOpenni2_GetImageByte
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
