/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class robotbase_vision_NativeFaceDetection */

#ifndef _Included_robotbase_vision_NativeFaceDetection
#define _Included_robotbase_vision_NativeFaceDetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     robotbase_vision_NativeFaceDetection
 * Method:    initCascade
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_robotbase_vision_NativeFaceDetection_initCascade
  (JNIEnv *, jclass, jstring);

/*
 * Class:     robotbase_vision_NativeFaceDetection
 * Method:    getPos
 * Signature: ([B[I[I[I[IJ)I
 */
JNIEXPORT jint JNICALL Java_robotbase_vision_NativeFaceDetection_getPos
  (JNIEnv *, jclass, jbyteArray, jintArray, jintArray, jintArray, jintArray, jlong);

/*
 * Class:     robotbase_vision_NativeFaceDetection
 * Method:    setPreviewSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_robotbase_vision_NativeFaceDetection_setPreviewSize
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
